### ISSUE TITLE
We Can Load Grids Faster

### ISSUE THREAD

**Issue by Azeezah** [kricheso/gridlock#34]
There is significant delay on the explore page load.  In the trendingGridsForUnregisteredUser function we can probably make the grids load faster by loading the user objects in parallel.  Currently, it awaits one user at a time before iterating to the next grid.

```
for (const doc of querySnapshot.docs) {
                    const dict = doc.data();
                    const user = await Firestore.get.user(dict.creatorId);
                    if (user === null) { return Error.firebaseFaliure(); }
                    ...
```
It may be worth it to investigate whether firebase allows us to combine this into one query with some kind of join operation on grids and users.

**Comment by kricheso** [comment]
Resolved
